# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InstitutionPluginTemplate
                                 A QGIS plugin
 Reusable QGIS plugin template with widget usage examples
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-02
        copyright            : (C) 2026 by Institution
        email                : simayataly0144@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InstitutionPluginTemplate class from file InstitutionPluginTemplate.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .institution_plugin_template import InstitutionPluginTemplate
    return InstitutionPluginTemplate(iface)
def classFactory(iface):
    """Load InstitutionPluginTemplate class from file InstitutionPluginTemplate.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .institution_plugin_template import InstitutionPluginTemplate
    return InstitutionPluginTemplate(iface)