# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InstitutionPluginTemplateDialog
                                 A QGIS plugin
 Reusable QGIS plugin template with widget usage examples
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Institution
        email                : simayataly0144@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .widgets import create_widget_examples

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'institution_plugin_template_dialog_base.ui'),
    from_imports=True,
    import_from='institution_plugin_template')


class InstitutionPluginTemplateDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InstitutionPluginTemplateDialog, self).__init__(parent)

        self.setupUi(self)
        self.widget_examples = create_widget_examples(self)

        self.pushButtonExample.clicked.connect(self.handle_button_click)
        self.sliderExample.valueChanged.connect(self.update_slider_value)
        self.openFileButton.clicked.connect(self.open_file)
        self.clearButton.clicked.connect(self.clear_form)
        self.runExampleButton.clicked.connect(self.run_example)
        self.tableWidgetExample.cellClicked.connect(self.handle_table_click)
      
    def handle_button_click(self):
        self.labelExample.setText(
            "Button clicked successfully."
        )
    def update_slider_value(self, value):
        self.sliderValueLabel.setText(
            f"Current Slider Value: {value}"
        )
        self.progressBarExample.setValue(value)
    def open_file(self):
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(
            self,
            "Metin Dosyası Seç",
            "",
            "Text Files (*.txt);;All Files (*)"
        )

        if not file_path:
            return

        try:
            with open(file_path, "r", encoding="utf-8", errors="replace") as file:
                content = file.read()

            self.textEditExample.setPlainText(content)

        except OSError as error:
            self.textEditExample.setPlainText(
                f"Dosya okunamadı:\n{error}"
            )
    def clear_form(self):
        self.lineEditExample.clear()
        self.textEditExample.clear()

        self.comboBoxExample.setCurrentIndex(0)

        self.checkBoxExample.setChecked(False)
        self.radioButtonExample.setChecked(False)

        self.spinBoxExample.setValue(0)
        self.doubleSpinBoxExample.setValue(0.0)

        self.sliderExample.setValue(0)
        self.progressBarExample.setValue(0)

        self.sliderValueLabel.setText(
            "Current Slider Value: 0"
        )

        self.labelExample.setText(
            "Form cleared successfully."
        )
    def run_example(self):
        entered_text = self.lineEditExample.text()
        selected_option = self.comboBoxExample.currentText()
        checkbox_checked = self.checkBoxExample.isChecked()
        radio_selected = self.radioButtonExample.isChecked()
        spin_value = self.spinBoxExample.value()
        double_spin_value = self.doubleSpinBoxExample.value()
        slider_value = self.sliderExample.value()
        selected_date = self.dateEditExample.date().toString("dd.MM.yyyy")
        selected_time = self.timeEditExample.time().toString("HH:mm:ss")
        selected_list_item = self.listWidgetExample.currentItem()
        if selected_list_item:
           list_value = selected_list_item.text()
        else:
           list_value = "No selection"
        summary = (
            f"Text: {entered_text}\n"
            f"ComboBox: {selected_option}\n"
            f"CheckBox: {checkbox_checked}\n"
            f"RadioButton: {radio_selected}\n"
            f"SpinBox: {spin_value}\n"
            f"DoubleSpinBox: {double_spin_value}\n"
            f"Slider: {slider_value}\n"
            f"ListWidget: {list_value}\n"
            f"DateEdit: {selected_date}\n"
            f"TimeEdit: {selected_time}\n"
        )

        self.textEditExample.setPlainText(summary)
    def handle_table_click(self, row, column):
        layer_item = self.tableWidgetExample.item(row, 0)
        features_item = self.tableWidgetExample.item(row, 1)

        if layer_item and features_item:
            self.labelExample.setText(
                f"Selected row: {layer_item.text()} - "
                f"Features: {features_item.text()}"
            )
    